from_ready_to_source_pim_configured:
  introduction:
    title: |
       This tool aims to help you to migrate your PIM 1.7 standard edition (either Community or Enterprise) to the new version 2.0.
       All your data will be migrated seamlessly. Your source PIM won't be updated nor touched. Instead, we'll perform the migration in a brand new PIM 2.0.
    rules: "In what follows, \"source PIM\" will refer to your current 1.7 PIM whereas \"destination PIM\" will refer to your future 2.0 PIM."
    start: "Here we are! A few questions before starting to migrate your PIM!"
  ask_source_pim_location:
    project_name:
      question: "What is the name of the project you want to migrate? Please choose a name with snake_case and alphanumeric characters. "
      error_message: "Your project name should use only alphanumeric and snake_case characters."
    pim_location:
      question: "Where is located your source PIM? "
  on_distant_configuration:
    hostname_question: "What is the hostname of the source PIM? For instance, myhost.domain.com. Don't put the http or https prefix please. ;)"
    hostname_error: "You should provide a valid hostname, for instance, myhost.domain.com. Don't put the http or https prefix please. ;)"
    ssh_port_question: "What is the SSH port of the source PIM? "
    ssh_port_error: "The SSH port should be an int. "
    ssh_user_question:  "What is the SSH user you want to connect with to the source PIM? "
    ssh_key_path_question: "What is the absolute path of the private SSH key able to connect to the source PIM? "
    ssh_key_path_error: "Your SSH key path should be an absolute one."
    composer_json_path_question: "What is the absolute path of the source PIM composer.json on the server? "
    composer_json_path_error: "Your composer.json path should be an absolute one."
  on_local_configuration:
    composer_json_path_question: "What is the absolute path of the source PIM composer.json on your computer? "
    composer_json_path_error: "Your composer.json path should be an absolute one."
from_source_pim_configured_to_source_pim_api_configured:
  on_source_pim_api_configuration:
    base_uri:
      question: "What is the base URI to request the API of the source PIM?"
      error_message: "You should provide a valid URI without parameters."
    client_id_question: "What is the client id to use to authenticate to the API of the source PIM?"
    secret_question: "What is the secret associated to this client?"
    user_name_question: "What is the username to use to authenticate to the API of the source PIM?"
    user_pwd_question: "What is the password associated to this username?"
from_source_pim_configured_to_source_pim_detected:
  on_source_pim_detected:
    result: "You want to migrate from %edition% edition with %storage% storage%inner%."
    an_enterprise: "an Enterprise"
    a_community: "a Community"
    orm: "ORM"
    hybrid: "Hybrid"
    and_inner_variation_bundle: " and the InnerVariationBundle"
from_source_pim_detected_to_all_accesses_granted:
  on_grant_all_accesses:
    first_ssh_key_error: "It looks like the private SSH key you have provided is not allowed to download the Akeneo Enterprise Edition."
    ssh_key_path_question: "What is the absolute path of the private SSH key allowed to connect to the Akeneo Enterprise Edition? "
    ssh_key_path_error: "Your SSH key path should be an absolute one."
    access_granted: "Access to the Akeneo %edition% Edition allowed."
    community: "Community"
    enterprise: "Enterprise"
from_all_accesses_granted_to_destination_pim_downloaded:
  on_ask_destination_pim_location:
    question: "How do you want to install the destination PIM? "
    docker_install: "Using docker-composer."
    archive_install: "I have a tar.gz archive, install it with docker."
    local_install: "I have already installed a destination PIM locally. "
    tar_gz_archive_path_question: "What is the absolute path of your tar.gz archive? "
    tar_gz_archive_path_error: "Your tar.gz archive path should be an absolute one."
    local_pim_path_question: "What is the absolute path of your local destination PIM? "
    local_pim_path_error: "Your local destination PIM path should be an absolute one."
  on_downloading:
    error: "Impossible to download your PIM: %exception%"
from_destination_pim_downloaded_to_destination_pim_installed:
  on_destination_pim_api_configuration:
    base_uri:
      question: "What is the base URI to request the API of the destination PIM?"
      error_message: "You should provide a valid URI without parameters."
from_destination_pim_requirements_checked_to_destination_pim_files_database_migrated:
  message: "Migrating files data..."
from_destination_pim_files_migrated_to_destination_pim_structure_migrated:
  message: "Migrating structure data..."
from_destination_pim_structure_migrated_to_destination_pim_family_migrated:
  message: "Migrating families data..."
from_destination_pim_family_migrated_to_destination_pim_system_migrated:
  message: "Migrating system data..."
from_destination_pim_system_migrated_to_destination_pim_job_migrated:
  message: "Migrating jobs data..."
from_destination_pim_job_migrated_to_destination_pim_group_migrated:
  message: "Migrating groups data..."
from_destination_pim_group_migrated_to_destination_pim_extra_data_migrated:
  message: "Migrating extra data..."
from_destination_pim_extra_data_migrated_to_destination_pim_reference_data_migrated:
  message: "Migrating reference data..."
from_destination_pim_reference_data_migrated_to_destination_pim_product_migrated:
  message: "Migrating products data..."
